service: node-worktest

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    PRODUCT_TABLE_NAME:  products-${self:provider.stage}

functions:
  create-product:
    handler: build/product/create-product/index.handler
    role: createProductRole
    events:
      - http:
          path: v1/product
          method: post

  get-product:
    handler: build/product/get-product/index.handler
    role: getProductRole
    events:
      - http:
          path: v1/product/{id}
          method: get

  transformer:
    handler: build/transformer/index.handler
    events:
      - http:
          path: v1/transformer
          method: get

resources:
  Resources:
    ProductsTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: products-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    createProductRole:
        Type: AWS::IAM::Role
        Properties:
          RoleName: create-product-role
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Principal:
                  Service: lambda.amazonaws.com
                Action: sts:AssumeRole
          Policies:
            - PolicyName: DynamoDBPutAndGetPolicy
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: Allow
                    Action:
                      - dynamodb:PutItem
                      - dynamodb:GetItem
                    Resource: "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/products-${self:provider.stage}"
                  - Effect: Allow
                    Action:
                      - logs:CreateLogGroup
                      - logs:CreateLogStream
                      - logs:PutLogEvents
                      - logs:TagResource
                    Resource:
                      - 'Fn::Join':
                        - ':'
                        -
                          - 'arn:aws:logs'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'log-group:/aws/lambda/*:*:*'

    getProductRole:
        Type: AWS::IAM::Role
        Properties:
          RoleName: get-product-role
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Principal:
                  Service: lambda.amazonaws.com
                Action: sts:AssumeRole
          Policies:
            - PolicyName: DynamoDBGetPolicy
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: Allow
                    Action:
                      - dynamodb:GetItem
                    Resource: "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/products-${self:provider.stage}"
                  - Effect: Allow
                    Action:
                      - logs:CreateLogGroup
                      - logs:CreateLogStream
                      - logs:PutLogEvents
                      - logs:TagResource
                    Resource:
                      - 'Fn::Join':
                        - ':'
                        -
                          - 'arn:aws:logs'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'log-group:/aws/lambda/*:*:*'

      